### ISSUE TITLE
Wallet stuck on specific height

### ISSUE THREAD

**Issue by GregoryGum** [Maize-Network/maize-blockchain#5]
I stack on specific level of Wallet and doesn't go up.
Also in log nothing about to update Wallet
No -> "Updated wallet peak to height"
![1](https://user-images.githubusercontent.com/72563378/129208624-c3728df2-00c0-4025-98cc-edae6fb6f6b4.png)

I reinstalled the application and I also re-sync the wallet. It always stack when arrive to specific height
After reinstall and re-sync I again see following
![2](https://user-images.githubusercontent.com/72563378/129208712-c6fc6fb1-89fc-4f66-9d6d-d041844aa23d.png)

**Comment by Maize-Network** [comment]
Please download last version and wait for sync. We had problem with internet On server tonight. Now all restored and we moving to another data center.--Отправлено из мобильной Яндекс.Почты12.08.2021, 16:52, "GregoryGum" ***@***.***>:
I stack on specific level of Wallet and doesn't go up.
Also in log nothing about to update Wallet
No -> "Updated wallet peak to height"

I reinstalled the application and I also re-sync the wallet. It always stack when arrive to specific height
After reinstall and re-sync I again see following

**Comment by GregoryGum** [comment]
I have re-sync db and wallet or only wallet will be enough?

**Comment by Maize-Network** [comment]
Try to wallet at first. --Отправлено из мобильной Яндекс.Почты12.08.2021, 17:07, "GregoryGum" ***@***.***>:
I have re-sync db and wallet or only wallet will be enough?
