### ISSUE TITLE
Only Got 0.25 XMZ Reward

### ISSUE THREAD

**Issue by wrjmhb21** [Maize-Network/maize-blockchain#6]
I am using the new NFT plot for farming, but only got 0.25 XMZ reward, where is the other reward, and how can I get it?

**Comment by Maize-Network** [comment]
Hello! Please go here. Automatic powershell script for returning 7/8 nft plots reward! https://maize.farm/nft7-8--Отправлено из мобильной Яндекс.Почты02.09.2021, 07:06, "wrjmhb21" ***@***.***>:
I am using the new NFT plot for farming, but only got 0.25 XMZ reward, where is the other reward, and how can I get it?
