### ISSUE TITLE
[BUG] 25 words instead of 24 when creating a new wallet

### ISSUE THREAD

**Issue by harambasapp** [Maize-Network/maize-blockchain#7]
You have the same issue as I have already reported on Chia-Network/chia-blockchain.

Chia-Network/chia-blockchain#8439

![maize error](https://user-images.githubusercontent.com/90500744/132955847-5b8d3f23-ca2f-4690-9703-e528d17bd346.PNG)

**Comment by Maize-Network** [comment]
Hello!We sent to dev. Thanks11.09.2021, 20:15, "Mladen Glisevic" ***@***.***>:
You have the same issue as I have already reported on Chia-Network/chia-blockchain.
Chia-Network/chia-blockchain#8439
