### ISSUE TITLE
Maize Wallet stuck on 0 and not update 

### ISSUE THREAD

**Issue by robertbigk** [Maize-Network/maize-blockchain#9]
Hi , 

I cannot update my wallet or wallet status not update. 

I completely remove all Maize, delete DB, Create a new wallet, import a wallet. Nothing work.

Full Node Status changes to full sync 

Wallet all time, not sync and 0
![mstsc_wlwQDbFZW0](https://user-images.githubusercontent.com/34956477/144717351-1b6ec3eb-d7f4-4602-be08-ba5bca886ad4.png)

**Comment by Maize-Network** [comment]
Hello!If you downloaded db for farming. Please delete db and start syncing from scratch --04.12.2021, 19:41, "robertbigk" ***@***.***>:
Hi ,
I cannot update my wallet or wallet status not update.
I completely remove all Maize, delete DB, Create a new wallet, import a wallet. Nothing work.
Full Node Status changes to full sync
Wallet all time, not sync and 0

**Comment by robertbigk** [comment]
Ok not work many clean install delete all config , db  download db and nothing work.

**Comment by Maize-Network** [comment]
Don’t download db. Start syncing from scratch --Отправлено из мобильной Яндекс.Почты04.12.2021, 20:18, "robertbigk" ***@***.***>:
Ok not work many clean install delete all config , db  download db and nothing work.

**Comment by robertbigk** [comment]
M8 I write You. Is not so simple I try in many ways "clean" install one of them is no any files just delete all and try to db sync and db synch but wallet no matter of what method I chose is stuck on 0 I delete all in AppData all folder user and nothing work. I got 11 different wallet and all work except this one.

**Comment by Maize-Network** [comment]
If you have firewall, allow wallet_node or take off firewall. If not help , try version 1.2.304.12.2021, 20:28, "robertbigk" ***@***.***>:
M8 I write You. Is not so simple I try in many ways "clean" install one of them is no any files just delete all and try to db sync and db synch but wallet no matter of what method I chose is stuck on 0 I delete all in AppData all folder user and nothing work. I got 11 different wallet and all work except this one.

**Comment by Maize-Network** [comment]
Please send your log file with wallet stuck issue 04.12.2021, 20:28, "robertbigk" ***@***.***>:
M8 I write You. Is not so simple I try in many ways "clean" install one of them is no any files just delete all and try to db sync and db synch but wallet no matter of what method I chose is stuck on 0 I delete all in AppData all folder user and nothing work. I got 11 different wallet and all work except this one.

**Comment by robertbigk** [comment]
[debug.log](https://github.com/Maize-Network/maize-blockchain/files/7654421/debug.log)

**Comment by Maize-Network** [comment]
from your log:Service wallet at port 8649 fully closedOpen port in firewall Please delete farming dband start syncing from scratch.We solve problem with db for downloading directly   04.12.2021, 21:25, "robertbigk" ***@***.***>: debug.log—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by robertbigk** [comment]
delete farming dband  is You mean delete all folder .maize in user windows?

**Comment by Maize-Network** [comment]
All files delete in .maize/mainnet/db Before , kill processes maize in task manager, if left04.12.2021, 21:38, "robertbigk" ***@***.***>:
delete farming dband  is You mean delete all folder .maize in user windows?

**Comment by robertbigk** [comment]
2021-12-04T19:40:14.323 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure in log what that mean?

**Comment by Maize-Network** [comment]
I don’t know.04.12.2021, 21:43, "robertbigk" ***@***.***>:
2021-12-04T19:40:14.323 daemon main                   : INFO     Waiting Daemon WebSocketServer closure in log what that mean?

**Comment by robertbigk** [comment]
ok than i delete all .maize and got wallet stuck nothing open and in log got this messedge what I write You

**Comment by Maize-Network** [comment]
Please uninstall MaizeDelete .maize folder Delete maize folders in appdataInstall maizeAnd start syncing of farming and wallet from scratch Don’t put db of farming in maize folder , which you downloaded from https://chiaforksblockchain.com--Отправлено из мобильной Яндекс.Почты04.12.2021, 21:47, "robertbigk" ***@***.***>:
ok than i delete all .maize and got wallet stuck nothing open and in log got this messedge what I write You

**Comment by robertbigk** [comment]
I delete all install on on fresh not work. I got BTCGreen , HddCoin , CryptoDodge , Flora , Flax , Chia, Cactus, Nchain , Stor , Staicoin  all work except Maize no matter what I do.

**Comment by Maize-Network** [comment]
--Please send screenshots of wallet tab and full node tab and all full node connections 04.12.2021, 22:49, "robertbigk" ***@***.***>:
I delete all install on on fresh not work. I got BTCGreen , HddCoin , CryptoDodge , Flora , Flax , Chia, Cactus, Nchain , Stor , Staicoin  all work except Maize no matter what I do.

**Comment by robertbigk** [comment]
![mstsc_LC8pOpBwrn](https://user-images.githubusercontent.com/34956477/144722849-d14ccc17-6fb6-49ba-9c51-01c9ffa7e177.png)
But now not synchro before delete i got fully sync

**Comment by Maize-Network** [comment]
Put peers file in .maize/mainnet/db and wait node connections see attach  04.12.2021, 22:53, "robertbigk" ***@***.***>: But now not synchro before delete i got fully sync—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by robertbigk** [comment]
any link where download node connection or You mean add manually? do You get some list address?

**Comment by Maize-Network** [comment]
I sent you peers file in previous letter04.12.2021, 23:10, "robertbigk" ***@***.***>:
any link where download node connection or You mean add manually? do You get some list address?

**Comment by robertbigk** [comment]
that link ?https://chiaforksblockchain.com--Отправлено is not open

**Comment by Maize-Network** [comment]
please download peer_table_node.sqlite file from this letter. Please see attachment 04.12.2021, 23:12, "robertbigk" ***@***.***>: that link ?https://chiaforksblockchain.com--Отправлено is not open—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by robertbigk** [comment]
Sorry still don't understand link does not work. No attachment for the post than from where do I need to download that?

**Comment by Maize-Network** [comment]
https://mega.nz/file/iu4yzJAI#5ArT7vBc12ThGcm98QJOHVUF-opLvJFttr3sKdxRnb8  04.12.2021, 23:19, "robertbigk" ***@***.***>: Sorry still don't understand link does not work. No attachment for the post than from where do I need to download that?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by robertbigk** [comment]
![mstsc_Vawpb2jDhb](https://user-images.githubusercontent.com/34956477/144724035-7fffed06-6db1-4883-81a1-b87a812cd51c.png)
![mstsc_hOZxL0Ohqm](https://user-images.githubusercontent.com/34956477/144724041-f316354b-9d9d-483e-a83f-901028a045df.png)
node add i wait 15 minutes and no any download still

**Comment by Maize-Network** [comment]
Syncing farming db is ok. WaitHave you wallet connection on port 8649?--Отправлено из мобильной Яндекс.Почты04.12.2021, 23:44, "robertbigk" ***@***.***>:


node add i wait 15 minutes and no any download still

**Comment by Maize-Network** [comment]
If all not help. Uninstall version 1.2.11 and all maize folders and install version 1.2.3--Отправлено из мобильной Яндекс.Почты04.12.2021, 23:44, "robertbigk" ***@***.***>:


node add i wait 15 minutes and no any download still

**Comment by robertbigk** [comment]
ok i install wallet from github 

https://github.com/Maize-Network/maize-blockchain/releases wheare find 1.2.3?

**Comment by robertbigk** [comment]
sorry is ease on Github ok i uninstall and try

**Comment by Maize-Network** [comment]
Scroll below in github 04.12.2021, 23:51, "robertbigk" ***@***.***>: ok i install wallet from githubhttps://github.com/Maize-Network/maize-blockchain/releases wheare find 1.2.3?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by robertbigk** [comment]
1.2.3 work:) thx for help

**Comment by Maize-Network** [comment]
Very good--Отправлено из мобильной Яндекс.Почты05.12.2021, 00:22, "robertbigk" ***@***.***>:
1.2.3 work:) thx for help

**Comment by d1Mm** [comment]
why default wallet rpc port was changed in version 1.2.11 from 8656 to 9656?
now it conflict with "cannabis-blockchain" wallet rpc

**Comment by Maize-Network** [comment]
Thanks for note. We will fix--Отправлено из мобильной Яндекс.Почты05.12.2021, 20:37, "d1Mm" ***@***.***>:
why default wallet rpc port was changed in version 1.2.11 from 8656 to 9656?
now it conflict with "cannabis-blockchain" wallet rpc
